# Generated by Django 4.2.1 on 2023-10-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_alter_spot_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('province_name',)},
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ('-date_add', '-likes')},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag_name',)},
        ),
        migrations.AlterField(
            model_name='spot',
            name='photo',
            field=models.ImageField(blank=True, upload_to='spot-photos'),
        ),
    ]
